// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package ru.splat.messages;

public final class Response {
  private Response() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ServiceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ServiceResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 services = 1;</code>
     */
    java.util.List<Integer> getServicesList();
    /**
     * <code>repeated int32 services = 1;</code>
     */
    int getServicesCount();
    /**
     * <code>repeated int32 services = 1;</code>
     */
    int getServices(int index);

    /**
     * <code>optional string stringResult = 2;</code>
     */
    String getStringResult();
    /**
     * <code>optional string stringResult = 2;</code>
     */
    com.google.protobuf.ByteString
        getStringResultBytes();

    /**
     * <code>optional int64 longResult = 3;</code>
     */
    long getLongResult();

    /**
     * <code>optional double doubleResult = 4;</code>
     */
    double getDoubleResult();

    /**
     * <code>optional bool booleanResult = 5;</code>
     */
    boolean getBooleanResult();

    public ServiceResponse.ResultOneofCase getResultOneofCase();
  }
  /**
   * Protobuf type {@code ServiceResult}
   */
  public  static final class ServiceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ServiceResult)
      ServiceResponseOrBuilder {
    // Use ServiceResult.newBuilder() to construct.
    private ServiceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ServiceResponse() {
      services_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ServiceResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                services_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              services_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                services_ = new java.util.ArrayList<Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                services_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();
              resultOneofCase_ = 2;
              resultOneof_ = s;
              break;
            }
            case 24: {
              resultOneofCase_ = 3;
              resultOneof_ = input.readInt64();
              break;
            }
            case 33: {
              resultOneofCase_ = 4;
              resultOneof_ = input.readDouble();
              break;
            }
            case 40: {
              resultOneofCase_ = 5;
              resultOneof_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = java.util.Collections.unmodifiableList(services_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Response.internal_static_ServiceResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Response.internal_static_ServiceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ServiceResponse.class, Builder.class);
    }

    private int bitField0_;
    private int resultOneofCase_ = 0;
    private Object resultOneof_;
    public enum ResultOneofCase
        implements com.google.protobuf.Internal.EnumLite {
      STRINGRESULT(2),
      LONGRESULT(3),
      DOUBLERESULT(4),
      BOOLEANRESULT(5),
      RESULTONEOF_NOT_SET(0);
      private final int value;
      private ResultOneofCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ResultOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static ResultOneofCase forNumber(int value) {
        switch (value) {
          case 2: return STRINGRESULT;
          case 3: return LONGRESULT;
          case 4: return DOUBLERESULT;
          case 5: return BOOLEANRESULT;
          case 0: return RESULTONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ResultOneofCase
    getResultOneofCase() {
      return ResultOneofCase.forNumber(
          resultOneofCase_);
    }

    public static final int SERVICES_FIELD_NUMBER = 1;
    private java.util.List<Integer> services_;
    /**
     * <code>repeated int32 services = 1;</code>
     */
    public java.util.List<Integer>
        getServicesList() {
      return services_;
    }
    /**
     * <code>repeated int32 services = 1;</code>
     */
    public int getServicesCount() {
      return services_.size();
    }
    /**
     * <code>repeated int32 services = 1;</code>
     */
    public int getServices(int index) {
      return services_.get(index);
    }
    private int servicesMemoizedSerializedSize = -1;

    public static final int STRINGRESULT_FIELD_NUMBER = 2;
    /**
     * <code>optional string stringResult = 2;</code>
     */
    public String getStringResult() {
      Object ref = "";
      if (resultOneofCase_ == 2) {
        ref = resultOneof_;
      }
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (resultOneofCase_ == 2) {
          resultOneof_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string stringResult = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStringResultBytes() {
      Object ref = "";
      if (resultOneofCase_ == 2) {
        ref = resultOneof_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        if (resultOneofCase_ == 2) {
          resultOneof_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LONGRESULT_FIELD_NUMBER = 3;
    /**
     * <code>optional int64 longResult = 3;</code>
     */
    public long getLongResult() {
      if (resultOneofCase_ == 3) {
        return (Long) resultOneof_;
      }
      return 0L;
    }

    public static final int DOUBLERESULT_FIELD_NUMBER = 4;
    /**
     * <code>optional double doubleResult = 4;</code>
     */
    public double getDoubleResult() {
      if (resultOneofCase_ == 4) {
        return (Double) resultOneof_;
      }
      return 0D;
    }

    public static final int BOOLEANRESULT_FIELD_NUMBER = 5;
    /**
     * <code>optional bool booleanResult = 5;</code>
     */
    public boolean getBooleanResult() {
      if (resultOneofCase_ == 5) {
        return (Boolean) resultOneof_;
      }
      return false;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getServicesList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(servicesMemoizedSerializedSize);
      }
      for (int i = 0; i < services_.size(); i++) {
        output.writeInt32NoTag(services_.get(i));
      }
      if (resultOneofCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resultOneof_);
      }
      if (resultOneofCase_ == 3) {
        output.writeInt64(
            3, (long)((Long) resultOneof_));
      }
      if (resultOneofCase_ == 4) {
        output.writeDouble(
            4, (double)((Double) resultOneof_));
      }
      if (resultOneofCase_ == 5) {
        output.writeBool(
            5, (boolean)((Boolean) resultOneof_));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < services_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(services_.get(i));
        }
        size += dataSize;
        if (!getServicesList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        servicesMemoizedSerializedSize = dataSize;
      }
      if (resultOneofCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resultOneof_);
      }
      if (resultOneofCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(
              3, (long)((Long) resultOneof_));
      }
      if (resultOneofCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              4, (double)((Double) resultOneof_));
      }
      if (resultOneofCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              5, (boolean)((Boolean) resultOneof_));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ServiceResponse)) {
        return super.equals(obj);
      }
      ServiceResponse other = (ServiceResponse) obj;

      boolean result = true;
      result = result && getServicesList()
          .equals(other.getServicesList());
      result = result && getResultOneofCase().equals(
          other.getResultOneofCase());
      if (!result) return false;
      switch (resultOneofCase_) {
        case 2:
          result = result && getStringResult()
              .equals(other.getStringResult());
          break;
        case 3:
          result = result && (getLongResult()
              == other.getLongResult());
          break;
        case 4:
          result = result && (
              Double.doubleToLongBits(getDoubleResult())
              == Double.doubleToLongBits(
                  other.getDoubleResult()));
          break;
        case 5:
          result = result && (getBooleanResult()
              == other.getBooleanResult());
          break;
        case 0:
        default:
      }
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getServicesCount() > 0) {
        hash = (37 * hash) + SERVICES_FIELD_NUMBER;
        hash = (53 * hash) + getServicesList().hashCode();
      }
      switch (resultOneofCase_) {
        case 2:
          hash = (37 * hash) + STRINGRESULT_FIELD_NUMBER;
          hash = (53 * hash) + getStringResult().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LONGRESULT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getLongResult());
          break;
        case 4:
          hash = (37 * hash) + DOUBLERESULT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              Double.doubleToLongBits(getDoubleResult()));
          break;
        case 5:
          hash = (37 * hash) + BOOLEANRESULT_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBooleanResult());
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ServiceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ServiceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ServiceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ServiceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ServiceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ServiceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ServiceResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ServiceResult)
        ServiceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Response.internal_static_ServiceResponse_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Response.internal_static_ServiceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ServiceResponse.class, Builder.class);
      }

      // Construct using ru.splat.messages.Response.ServiceResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        resultOneofCase_ = 0;
        resultOneof_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Response.internal_static_ServiceResponse_descriptor;
      }

      public ServiceResponse getDefaultInstanceForType() {
        return ServiceResponse.getDefaultInstance();
      }

      public ServiceResponse build() {
        ServiceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ServiceResponse buildPartial() {
        ServiceResponse result = new ServiceResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = java.util.Collections.unmodifiableList(services_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.services_ = services_;
        if (resultOneofCase_ == 2) {
          result.resultOneof_ = resultOneof_;
        }
        if (resultOneofCase_ == 3) {
          result.resultOneof_ = resultOneof_;
        }
        if (resultOneofCase_ == 4) {
          result.resultOneof_ = resultOneof_;
        }
        if (resultOneofCase_ == 5) {
          result.resultOneof_ = resultOneof_;
        }
        result.bitField0_ = to_bitField0_;
        result.resultOneofCase_ = resultOneofCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ServiceResponse) {
          return mergeFrom((ServiceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ServiceResponse other) {
        if (other == ServiceResponse.getDefaultInstance()) return this;
        if (!other.services_.isEmpty()) {
          if (services_.isEmpty()) {
            services_ = other.services_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureServicesIsMutable();
            services_.addAll(other.services_);
          }
          onChanged();
        }
        switch (other.getResultOneofCase()) {
          case STRINGRESULT: {
            resultOneofCase_ = 2;
            resultOneof_ = other.resultOneof_;
            onChanged();
            break;
          }
          case LONGRESULT: {
            setLongResult(other.getLongResult());
            break;
          }
          case DOUBLERESULT: {
            setDoubleResult(other.getDoubleResult());
            break;
          }
          case BOOLEANRESULT: {
            setBooleanResult(other.getBooleanResult());
            break;
          }
          case RESULTONEOF_NOT_SET: {
            break;
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ServiceResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ServiceResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int resultOneofCase_ = 0;
      private Object resultOneof_;
      public ResultOneofCase
          getResultOneofCase() {
        return ResultOneofCase.forNumber(
            resultOneofCase_);
      }

      public Builder clearResultOneof() {
        resultOneofCase_ = 0;
        resultOneof_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.util.List<Integer> services_ = java.util.Collections.emptyList();
      private void ensureServicesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          services_ = new java.util.ArrayList<Integer>(services_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public java.util.List<Integer>
          getServicesList() {
        return java.util.Collections.unmodifiableList(services_);
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public int getServicesCount() {
        return services_.size();
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public int getServices(int index) {
        return services_.get(index);
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder setServices(
          int index, int value) {
        ensureServicesIsMutable();
        services_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder addServices(int value) {
        ensureServicesIsMutable();
        services_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder addAllServices(
          Iterable<? extends Integer> values) {
        ensureServicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, services_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 services = 1;</code>
       */
      public Builder clearServices() {
        services_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      /**
       * <code>optional string stringResult = 2;</code>
       */
      public String getStringResult() {
        Object ref = "";
        if (resultOneofCase_ == 2) {
          ref = resultOneof_;
        }
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (resultOneofCase_ == 2) {
            resultOneof_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string stringResult = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStringResultBytes() {
        Object ref = "";
        if (resultOneofCase_ == 2) {
          ref = resultOneof_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          if (resultOneofCase_ == 2) {
            resultOneof_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string stringResult = 2;</code>
       */
      public Builder setStringResult(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  resultOneofCase_ = 2;
        resultOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string stringResult = 2;</code>
       */
      public Builder clearStringResult() {
        if (resultOneofCase_ == 2) {
          resultOneofCase_ = 0;
          resultOneof_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional string stringResult = 2;</code>
       */
      public Builder setStringResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        resultOneofCase_ = 2;
        resultOneof_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional int64 longResult = 3;</code>
       */
      public long getLongResult() {
        if (resultOneofCase_ == 3) {
          return (Long) resultOneof_;
        }
        return 0L;
      }
      /**
       * <code>optional int64 longResult = 3;</code>
       */
      public Builder setLongResult(long value) {
        resultOneofCase_ = 3;
        resultOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 longResult = 3;</code>
       */
      public Builder clearLongResult() {
        if (resultOneofCase_ == 3) {
          resultOneofCase_ = 0;
          resultOneof_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional double doubleResult = 4;</code>
       */
      public double getDoubleResult() {
        if (resultOneofCase_ == 4) {
          return (Double) resultOneof_;
        }
        return 0D;
      }
      /**
       * <code>optional double doubleResult = 4;</code>
       */
      public Builder setDoubleResult(double value) {
        resultOneofCase_ = 4;
        resultOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double doubleResult = 4;</code>
       */
      public Builder clearDoubleResult() {
        if (resultOneofCase_ == 4) {
          resultOneofCase_ = 0;
          resultOneof_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>optional bool booleanResult = 5;</code>
       */
      public boolean getBooleanResult() {
        if (resultOneofCase_ == 5) {
          return (Boolean) resultOneof_;
        }
        return false;
      }
      /**
       * <code>optional bool booleanResult = 5;</code>
       */
      public Builder setBooleanResult(boolean value) {
        resultOneofCase_ = 5;
        resultOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool booleanResult = 5;</code>
       */
      public Builder clearBooleanResult() {
        if (resultOneofCase_ == 5) {
          resultOneofCase_ = 0;
          resultOneof_ = null;
          onChanged();
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:ServiceResult)
    }

    // @@protoc_insertion_point(class_scope:ServiceResult)
    private static final ServiceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ServiceResponse();
    }

    public static ServiceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ServiceResponse>
        PARSER = new com.google.protobuf.AbstractParser<ServiceResponse>() {
      public ServiceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ServiceResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ServiceResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ServiceResponse> getParserForType() {
      return PARSER;
    }

    public ServiceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Response.proto\"\222\001\n\017ServiceResponse\022\020\n\010" +
      "services\030\001 \003(\005\022\026\n\014stringResult\030\002 \001(\tH\000\022\024" +
      "\n\nlongResult\030\003 \001(\003H\000\022\026\n\014doubleResult\030\004 \001" +
      "(\001H\000\022\027\n\rbooleanResult\030\005 \001(\010H\000B\016\n\014result_" +
      "oneofB\035\n\021ru.splat.messagesB\010Responseb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ServiceResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ServiceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceResponse_descriptor,
        new String[] { "Services", "StringResult", "LongResult", "DoubleResult", "BooleanResult", "ResultOneof", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
