// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PunterReq.proto

package ru.splat.Punter.protobuf;

public final class PunterReq {
  private PunterReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PunterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string local_task = 1;
    /**
     * <code>required string local_task = 1;</code>
     */
    boolean hasLocalTask();
    /**
     * <code>required string local_task = 1;</code>
     */
    String getLocalTask();
    /**
     * <code>required string local_task = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocalTaskBytes();

    // optional int32 punter_id = 3;
    /**
     * <code>optional int32 punter_id = 3;</code>
     */
    boolean hasPunterId();
    /**
     * <code>optional int32 punter_id = 3;</code>
     */
    int getPunterId();
  }
  /**
   * Protobuf type {@code tutorial.Punter}
   */
  public static final class Punter extends
      com.google.protobuf.GeneratedMessage
      implements PunterOrBuilder {
    // Use Punter.newBuilder() to construct.
    private Punter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Punter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Punter defaultInstance;
    public static Punter getDefaultInstance() {
      return defaultInstance;
    }

    public Punter getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Punter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              localTask_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              punterId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PunterReq.internal_static_tutorial_Punter_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PunterReq.internal_static_tutorial_Punter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Punter.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Punter> PARSER =
        new com.google.protobuf.AbstractParser<Punter>() {
      public Punter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Punter(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Punter> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string local_task = 1;
    public static final int LOCAL_TASK_FIELD_NUMBER = 1;
    private Object localTask_;
    /**
     * <code>required string local_task = 1;</code>
     */
    public boolean hasLocalTask() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string local_task = 1;</code>
     */
    public String getLocalTask() {
      Object ref = localTask_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localTask_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string local_task = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocalTaskBytes() {
      Object ref = localTask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        localTask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 punter_id = 3;
    public static final int PUNTER_ID_FIELD_NUMBER = 3;
    private int punterId_;
    /**
     * <code>optional int32 punter_id = 3;</code>
     */
    public boolean hasPunterId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 punter_id = 3;</code>
     */
    public int getPunterId() {
      return punterId_;
    }

    private void initFields() {
      localTask_ = "";
      punterId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLocalTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getLocalTaskBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, punterId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getLocalTaskBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, punterId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Punter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Punter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Punter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Punter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Punter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Punter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Punter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Punter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Punter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Punter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Punter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Punter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements PunterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PunterReq.internal_static_tutorial_Punter_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PunterReq.internal_static_tutorial_Punter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Punter.class, Builder.class);
      }

      // Construct using ru.splat.protobuf.PunterReq.Punter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        localTask_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        punterId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PunterReq.internal_static_tutorial_Punter_descriptor;
      }

      public Punter getDefaultInstanceForType() {
        return Punter.getDefaultInstance();
      }

      public Punter build() {
        Punter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Punter buildPartial() {
        Punter result = new Punter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.localTask_ = localTask_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.punterId_ = punterId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Punter) {
          return mergeFrom((Punter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Punter other) {
        if (other == Punter.getDefaultInstance()) return this;
        if (other.hasLocalTask()) {
          bitField0_ |= 0x00000001;
          localTask_ = other.localTask_;
          onChanged();
        }
        if (other.hasPunterId()) {
          setPunterId(other.getPunterId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLocalTask()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Punter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Punter) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string local_task = 1;
      private Object localTask_ = "";
      /**
       * <code>required string local_task = 1;</code>
       */
      public boolean hasLocalTask() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string local_task = 1;</code>
       */
      public String getLocalTask() {
        Object ref = localTask_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localTask_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string local_task = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocalTaskBytes() {
        Object ref = localTask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          localTask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string local_task = 1;</code>
       */
      public Builder setLocalTask(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string local_task = 1;</code>
       */
      public Builder clearLocalTask() {
        bitField0_ = (bitField0_ & ~0x00000001);
        localTask_ = getDefaultInstance().getLocalTask();
        onChanged();
        return this;
      }
      /**
       * <code>required string local_task = 1;</code>
       */
      public Builder setLocalTaskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        localTask_ = value;
        onChanged();
        return this;
      }

      // optional int32 punter_id = 3;
      private int punterId_ ;
      /**
       * <code>optional int32 punter_id = 3;</code>
       */
      public boolean hasPunterId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 punter_id = 3;</code>
       */
      public int getPunterId() {
        return punterId_;
      }
      /**
       * <code>optional int32 punter_id = 3;</code>
       */
      public Builder setPunterId(int value) {
        bitField0_ |= 0x00000002;
        punterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 punter_id = 3;</code>
       */
      public Builder clearPunterId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        punterId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Punter)
    }

    static {
      defaultInstance = new Punter(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Punter)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Punter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Punter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017PunterReq.proto\022\010tutorial\"/\n\006Punter\022\022\n" +
      "\nlocal_task\030\001 \002(\t\022\021\n\tpunter_id\030\003 \001(\005B\036\n\021" +
      "ru.splat.protobufB\tPunterReq"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Punter_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Punter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Punter_descriptor,
              new String[] { "LocalTask", "PunterId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
