// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BetReq.proto

package ru.splat.Bet.protobuf;

public final class BetReq {
  private BetReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 punterId = 1;
    /**
     * <code>required int32 punterId = 1;</code>
     */
    boolean hasPunterId();
    /**
     * <code>required int32 punterId = 1;</code>
     */
    int getPunterId();

    // required int32 betSum = 2;
    /**
     * <code>required int32 betSum = 2;</code>
     */
    boolean hasBetSum();
    /**
     * <code>required int32 betSum = 2;</code>
     */
    int getBetSum();

    // required string localTask = 3;
    /**
     * <code>required string localTask = 3;</code>
     */
    boolean hasLocalTask();
    /**
     * <code>required string localTask = 3;</code>
     */
    String getLocalTask();
    /**
     * <code>required string localTask = 3;</code>
     */
    com.google.protobuf.ByteString
        getLocalTaskBytes();

    // repeated .tutorial.Bet.BetOutcome betOutcome = 4;
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    java.util.List<Bet.BetOutcome>
        getBetOutcomeList();
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    Bet.BetOutcome getBetOutcome(int index);
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    int getBetOutcomeCount();
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    java.util.List<? extends Bet.BetOutcomeOrBuilder>
        getBetOutcomeOrBuilderList();
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    Bet.BetOutcomeOrBuilder getBetOutcomeOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code tutorial.Bet}
   */
  public static final class Bet extends
      com.google.protobuf.GeneratedMessage
      implements BetOrBuilder {
    // Use Bet.newBuilder() to construct.
    private Bet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Bet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Bet defaultInstance;
    public static Bet getDefaultInstance() {
      return defaultInstance;
    }

    public Bet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Bet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              punterId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              betSum_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              localTask_ = input.readBytes();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                betOutcome_ = new java.util.ArrayList<BetOutcome>();
                mutable_bitField0_ |= 0x00000008;
              }
              betOutcome_.add(input.readMessage(BetOutcome.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          betOutcome_ = java.util.Collections.unmodifiableList(betOutcome_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BetReq.internal_static_tutorial_Bet_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BetReq.internal_static_tutorial_Bet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Bet.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Bet> PARSER =
        new com.google.protobuf.AbstractParser<Bet>() {
      public Bet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bet(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Bet> getParserForType() {
      return PARSER;
    }

    public interface BetOutcomeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required int32 eventId = 1;
      /**
       * <code>required int32 eventId = 1;</code>
       */
      boolean hasEventId();
      /**
       * <code>required int32 eventId = 1;</code>
       */
      int getEventId();

      // required int32 id = 2;
      /**
       * <code>required int32 id = 2;</code>
       */
      boolean hasId();
      /**
       * <code>required int32 id = 2;</code>
       */
      int getId();

      // required double koef = 3;
      /**
       * <code>required double koef = 3;</code>
       */
      boolean hasKoef();
      /**
       * <code>required double koef = 3;</code>
       */
      double getKoef();
    }
    /**
     * Protobuf type {@code tutorial.Bet.BetOutcome}
     */
    public static final class BetOutcome extends
        com.google.protobuf.GeneratedMessage
        implements BetOutcomeOrBuilder {
      // Use BetOutcome.newBuilder() to construct.
      private BetOutcome(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private BetOutcome(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final BetOutcome defaultInstance;
      public static BetOutcome getDefaultInstance() {
        return defaultInstance;
      }

      public BetOutcome getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private BetOutcome(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                eventId_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                id_ = input.readInt32();
                break;
              }
              case 25: {
                bitField0_ |= 0x00000004;
                koef_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BetReq.internal_static_tutorial_Bet_BetOutcome_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BetReq.internal_static_tutorial_Bet_BetOutcome_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                BetOutcome.class, Builder.class);
      }

      public static com.google.protobuf.Parser<BetOutcome> PARSER =
          new com.google.protobuf.AbstractParser<BetOutcome>() {
        public BetOutcome parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new BetOutcome(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<BetOutcome> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required int32 eventId = 1;
      public static final int EVENTID_FIELD_NUMBER = 1;
      private int eventId_;
      /**
       * <code>required int32 eventId = 1;</code>
       */
      public boolean hasEventId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 eventId = 1;</code>
       */
      public int getEventId() {
        return eventId_;
      }

      // required int32 id = 2;
      public static final int ID_FIELD_NUMBER = 2;
      private int id_;
      /**
       * <code>required int32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }

      // required double koef = 3;
      public static final int KOEF_FIELD_NUMBER = 3;
      private double koef_;
      /**
       * <code>required double koef = 3;</code>
       */
      public boolean hasKoef() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double koef = 3;</code>
       */
      public double getKoef() {
        return koef_;
      }

      private void initFields() {
        eventId_ = 0;
        id_ = 0;
        koef_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasEventId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasKoef()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, eventId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, id_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeDouble(3, koef_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, eventId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, id_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(3, koef_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static BetOutcome parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static BetOutcome parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static BetOutcome parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static BetOutcome parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static BetOutcome parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static BetOutcome parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static BetOutcome parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static BetOutcome parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static BetOutcome parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static BetOutcome parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(BetOutcome prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tutorial.Bet.BetOutcome}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements BetOutcomeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return BetReq.internal_static_tutorial_Bet_BetOutcome_descriptor;
        }

        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return BetReq.internal_static_tutorial_Bet_BetOutcome_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  BetOutcome.class, Builder.class);
        }

        // Construct using ru.splat.Bet.protobuf.BetReq.Bet.BetOutcome.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          eventId_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          koef_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return BetReq.internal_static_tutorial_Bet_BetOutcome_descriptor;
        }

        public BetOutcome getDefaultInstanceForType() {
          return BetOutcome.getDefaultInstance();
        }

        public BetOutcome build() {
          BetOutcome result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public BetOutcome buildPartial() {
          BetOutcome result = new BetOutcome(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.eventId_ = eventId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.koef_ = koef_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof BetOutcome) {
            return mergeFrom((BetOutcome)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(BetOutcome other) {
          if (other == BetOutcome.getDefaultInstance()) return this;
          if (other.hasEventId()) {
            setEventId(other.getEventId());
          }
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasKoef()) {
            setKoef(other.getKoef());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasEventId()) {
            
            return false;
          }
          if (!hasId()) {
            
            return false;
          }
          if (!hasKoef()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          BetOutcome parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (BetOutcome) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required int32 eventId = 1;
        private int eventId_ ;
        /**
         * <code>required int32 eventId = 1;</code>
         */
        public boolean hasEventId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 eventId = 1;</code>
         */
        public int getEventId() {
          return eventId_;
        }
        /**
         * <code>required int32 eventId = 1;</code>
         */
        public Builder setEventId(int value) {
          bitField0_ |= 0x00000001;
          eventId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 eventId = 1;</code>
         */
        public Builder clearEventId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          eventId_ = 0;
          onChanged();
          return this;
        }

        // required int32 id = 2;
        private int id_ ;
        /**
         * <code>required int32 id = 2;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 id = 2;</code>
         */
        public int getId() {
          return id_;
        }
        /**
         * <code>required int32 id = 2;</code>
         */
        public Builder setId(int value) {
          bitField0_ |= 0x00000002;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 id = 2;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          id_ = 0;
          onChanged();
          return this;
        }

        // required double koef = 3;
        private double koef_ ;
        /**
         * <code>required double koef = 3;</code>
         */
        public boolean hasKoef() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required double koef = 3;</code>
         */
        public double getKoef() {
          return koef_;
        }
        /**
         * <code>required double koef = 3;</code>
         */
        public Builder setKoef(double value) {
          bitField0_ |= 0x00000004;
          koef_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required double koef = 3;</code>
         */
        public Builder clearKoef() {
          bitField0_ = (bitField0_ & ~0x00000004);
          koef_ = 0D;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tutorial.Bet.BetOutcome)
      }

      static {
        defaultInstance = new BetOutcome(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:tutorial.Bet.BetOutcome)
    }

    private int bitField0_;
    // required int32 punterId = 1;
    public static final int PUNTERID_FIELD_NUMBER = 1;
    private int punterId_;
    /**
     * <code>required int32 punterId = 1;</code>
     */
    public boolean hasPunterId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 punterId = 1;</code>
     */
    public int getPunterId() {
      return punterId_;
    }

    // required int32 betSum = 2;
    public static final int BETSUM_FIELD_NUMBER = 2;
    private int betSum_;
    /**
     * <code>required int32 betSum = 2;</code>
     */
    public boolean hasBetSum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 betSum = 2;</code>
     */
    public int getBetSum() {
      return betSum_;
    }

    // required string localTask = 3;
    public static final int LOCALTASK_FIELD_NUMBER = 3;
    private Object localTask_;
    /**
     * <code>required string localTask = 3;</code>
     */
    public boolean hasLocalTask() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string localTask = 3;</code>
     */
    public String getLocalTask() {
      Object ref = localTask_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localTask_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string localTask = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocalTaskBytes() {
      Object ref = localTask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        localTask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .tutorial.Bet.BetOutcome betOutcome = 4;
    public static final int BETOUTCOME_FIELD_NUMBER = 4;
    private java.util.List<BetOutcome> betOutcome_;
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    public java.util.List<BetOutcome> getBetOutcomeList() {
      return betOutcome_;
    }
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    public java.util.List<? extends BetOutcomeOrBuilder>
        getBetOutcomeOrBuilderList() {
      return betOutcome_;
    }
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    public int getBetOutcomeCount() {
      return betOutcome_.size();
    }
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    public BetOutcome getBetOutcome(int index) {
      return betOutcome_.get(index);
    }
    /**
     * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
     */
    public BetOutcomeOrBuilder getBetOutcomeOrBuilder(
        int index) {
      return betOutcome_.get(index);
    }

    private void initFields() {
      punterId_ = 0;
      betSum_ = 0;
      localTask_ = "";
      betOutcome_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPunterId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBetSum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBetOutcomeCount(); i++) {
        if (!getBetOutcome(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, punterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, betSum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLocalTaskBytes());
      }
      for (int i = 0; i < betOutcome_.size(); i++) {
        output.writeMessage(4, betOutcome_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, punterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, betSum_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLocalTaskBytes());
      }
      for (int i = 0; i < betOutcome_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, betOutcome_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Bet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Bet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Bet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Bet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Bet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Bet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Bet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Bet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Bet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Bet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Bet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Bet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BetReq.internal_static_tutorial_Bet_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BetReq.internal_static_tutorial_Bet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Bet.class, Builder.class);
      }

      // Construct using ru.splat.Bet.protobuf.BetReq.Bet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBetOutcomeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        punterId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        betSum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        localTask_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (betOutcomeBuilder_ == null) {
          betOutcome_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          betOutcomeBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BetReq.internal_static_tutorial_Bet_descriptor;
      }

      public Bet getDefaultInstanceForType() {
        return Bet.getDefaultInstance();
      }

      public Bet build() {
        Bet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Bet buildPartial() {
        Bet result = new Bet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.punterId_ = punterId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.betSum_ = betSum_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.localTask_ = localTask_;
        if (betOutcomeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            betOutcome_ = java.util.Collections.unmodifiableList(betOutcome_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.betOutcome_ = betOutcome_;
        } else {
          result.betOutcome_ = betOutcomeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Bet) {
          return mergeFrom((Bet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Bet other) {
        if (other == Bet.getDefaultInstance()) return this;
        if (other.hasPunterId()) {
          setPunterId(other.getPunterId());
        }
        if (other.hasBetSum()) {
          setBetSum(other.getBetSum());
        }
        if (other.hasLocalTask()) {
          bitField0_ |= 0x00000004;
          localTask_ = other.localTask_;
          onChanged();
        }
        if (betOutcomeBuilder_ == null) {
          if (!other.betOutcome_.isEmpty()) {
            if (betOutcome_.isEmpty()) {
              betOutcome_ = other.betOutcome_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureBetOutcomeIsMutable();
              betOutcome_.addAll(other.betOutcome_);
            }
            onChanged();
          }
        } else {
          if (!other.betOutcome_.isEmpty()) {
            if (betOutcomeBuilder_.isEmpty()) {
              betOutcomeBuilder_.dispose();
              betOutcomeBuilder_ = null;
              betOutcome_ = other.betOutcome_;
              bitField0_ = (bitField0_ & ~0x00000008);
              betOutcomeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBetOutcomeFieldBuilder() : null;
            } else {
              betOutcomeBuilder_.addAllMessages(other.betOutcome_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPunterId()) {
          
          return false;
        }
        if (!hasBetSum()) {
          
          return false;
        }
        if (!hasLocalTask()) {
          
          return false;
        }
        for (int i = 0; i < getBetOutcomeCount(); i++) {
          if (!getBetOutcome(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Bet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Bet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 punterId = 1;
      private int punterId_ ;
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public boolean hasPunterId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public int getPunterId() {
        return punterId_;
      }
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public Builder setPunterId(int value) {
        bitField0_ |= 0x00000001;
        punterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public Builder clearPunterId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        punterId_ = 0;
        onChanged();
        return this;
      }

      // required int32 betSum = 2;
      private int betSum_ ;
      /**
       * <code>required int32 betSum = 2;</code>
       */
      public boolean hasBetSum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 betSum = 2;</code>
       */
      public int getBetSum() {
        return betSum_;
      }
      /**
       * <code>required int32 betSum = 2;</code>
       */
      public Builder setBetSum(int value) {
        bitField0_ |= 0x00000002;
        betSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 betSum = 2;</code>
       */
      public Builder clearBetSum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        betSum_ = 0;
        onChanged();
        return this;
      }

      // required string localTask = 3;
      private Object localTask_ = "";
      /**
       * <code>required string localTask = 3;</code>
       */
      public boolean hasLocalTask() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public String getLocalTask() {
        Object ref = localTask_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localTask_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLocalTaskBytes() {
        Object ref = localTask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          localTask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public Builder setLocalTask(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public Builder clearLocalTask() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localTask_ = getDefaultInstance().getLocalTask();
        onChanged();
        return this;
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public Builder setLocalTaskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localTask_ = value;
        onChanged();
        return this;
      }

      // repeated .tutorial.Bet.BetOutcome betOutcome = 4;
      private java.util.List<BetOutcome> betOutcome_ =
        java.util.Collections.emptyList();
      private void ensureBetOutcomeIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          betOutcome_ = new java.util.ArrayList<BetOutcome>(betOutcome_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          BetOutcome, BetOutcome.Builder, BetOutcomeOrBuilder> betOutcomeBuilder_;

      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public java.util.List<BetOutcome> getBetOutcomeList() {
        if (betOutcomeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(betOutcome_);
        } else {
          return betOutcomeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public int getBetOutcomeCount() {
        if (betOutcomeBuilder_ == null) {
          return betOutcome_.size();
        } else {
          return betOutcomeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public BetOutcome getBetOutcome(int index) {
        if (betOutcomeBuilder_ == null) {
          return betOutcome_.get(index);
        } else {
          return betOutcomeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder setBetOutcome(
          int index, BetOutcome value) {
        if (betOutcomeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetOutcomeIsMutable();
          betOutcome_.set(index, value);
          onChanged();
        } else {
          betOutcomeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder setBetOutcome(
          int index, BetOutcome.Builder builderForValue) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.set(index, builderForValue.build());
          onChanged();
        } else {
          betOutcomeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder addBetOutcome(BetOutcome value) {
        if (betOutcomeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetOutcomeIsMutable();
          betOutcome_.add(value);
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder addBetOutcome(
          int index, BetOutcome value) {
        if (betOutcomeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetOutcomeIsMutable();
          betOutcome_.add(index, value);
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder addBetOutcome(
          BetOutcome.Builder builderForValue) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.add(builderForValue.build());
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder addBetOutcome(
          int index, BetOutcome.Builder builderForValue) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.add(index, builderForValue.build());
          onChanged();
        } else {
          betOutcomeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder addAllBetOutcome(
          Iterable<? extends BetOutcome> values) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          super.addAll(values, betOutcome_);
          onChanged();
        } else {
          betOutcomeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder clearBetOutcome() {
        if (betOutcomeBuilder_ == null) {
          betOutcome_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          betOutcomeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public Builder removeBetOutcome(int index) {
        if (betOutcomeBuilder_ == null) {
          ensureBetOutcomeIsMutable();
          betOutcome_.remove(index);
          onChanged();
        } else {
          betOutcomeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public BetOutcome.Builder getBetOutcomeBuilder(
          int index) {
        return getBetOutcomeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public BetOutcomeOrBuilder getBetOutcomeOrBuilder(
          int index) {
        if (betOutcomeBuilder_ == null) {
          return betOutcome_.get(index);  } else {
          return betOutcomeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public java.util.List<? extends BetOutcomeOrBuilder>
           getBetOutcomeOrBuilderList() {
        if (betOutcomeBuilder_ != null) {
          return betOutcomeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(betOutcome_);
        }
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public BetOutcome.Builder addBetOutcomeBuilder() {
        return getBetOutcomeFieldBuilder().addBuilder(
            BetOutcome.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public BetOutcome.Builder addBetOutcomeBuilder(
          int index) {
        return getBetOutcomeFieldBuilder().addBuilder(
            index, BetOutcome.getDefaultInstance());
      }
      /**
       * <code>repeated .tutorial.Bet.BetOutcome betOutcome = 4;</code>
       */
      public java.util.List<BetOutcome.Builder>
           getBetOutcomeBuilderList() {
        return getBetOutcomeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          BetOutcome, BetOutcome.Builder, BetOutcomeOrBuilder>
          getBetOutcomeFieldBuilder() {
        if (betOutcomeBuilder_ == null) {
          betOutcomeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              BetOutcome, BetOutcome.Builder, BetOutcomeOrBuilder>(
                  betOutcome_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          betOutcome_ = null;
        }
        return betOutcomeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Bet)
    }

    static {
      defaultInstance = new Bet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Bet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Bet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Bet_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Bet_BetOutcome_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Bet_BetOutcome_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014BetReq.proto\022\010tutorial\"\241\001\n\003Bet\022\020\n\010punt" +
      "erId\030\001 \002(\005\022\016\n\006betSum\030\002 \002(\005\022\021\n\tlocalTask\030" +
      "\003 \002(\t\022,\n\nbetOutcome\030\004 \003(\0132\030.tutorial.Bet" +
      ".BetOutcome\0327\n\nBetOutcome\022\017\n\007eventId\030\001 \002" +
      "(\005\022\n\n\002id\030\002 \002(\005\022\014\n\004koef\030\003 \002(\001B\037\n\025ru.splat" +
      ".Bet.protobufB\006BetReq"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Bet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Bet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Bet_descriptor,
              new String[] { "PunterId", "BetSum", "LocalTask", "BetOutcome", });
          internal_static_tutorial_Bet_BetOutcome_descriptor =
            internal_static_tutorial_Bet_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_Bet_BetOutcome_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Bet_BetOutcome_descriptor,
              new String[] { "EventId", "Id", "Koef", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
