// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BillingReq.proto

package ru.splat.Billing.protobuf;

public final class BallanceReq {
  private BallanceReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BillingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 punterId = 1;
    /**
     * <code>required int32 punterId = 1;</code>
     */
    boolean hasPunterId();
    /**
     * <code>required int32 punterId = 1;</code>
     */
    int getPunterId();

    // required int32 ballance = 2;
    /**
     * <code>required int32 ballance = 2;</code>
     */
    boolean hasBallance();
    /**
     * <code>required int32 ballance = 2;</code>
     */
    int getBallance();

    // required string localTask = 3;
    /**
     * <code>required string localTask = 3;</code>
     */
    boolean hasLocalTask();
    /**
     * <code>required string localTask = 3;</code>
     */
    String getLocalTask();
    /**
     * <code>required string localTask = 3;</code>
     */
    com.google.protobuf.ByteString
        getLocalTaskBytes();
  }
  /**
   * Protobuf type {@code tutorial.Billing}
   */
  public static final class Billing extends
      com.google.protobuf.GeneratedMessage
      implements BillingOrBuilder {
    // Use Billing.newBuilder() to construct.
    private Billing(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Billing(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Billing defaultInstance;
    public static Billing getDefaultInstance() {
      return defaultInstance;
    }

    public Billing getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Billing(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              punterId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              ballance_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              localTask_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BallanceReq.internal_static_tutorial_Billing_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BallanceReq.internal_static_tutorial_Billing_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Billing.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Billing> PARSER =
        new com.google.protobuf.AbstractParser<Billing>() {
      public Billing parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Billing(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Billing> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 punterId = 1;
    public static final int PUNTERID_FIELD_NUMBER = 1;
    private int punterId_;
    /**
     * <code>required int32 punterId = 1;</code>
     */
    public boolean hasPunterId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 punterId = 1;</code>
     */
    public int getPunterId() {
      return punterId_;
    }

    // required int32 ballance = 2;
    public static final int BALLANCE_FIELD_NUMBER = 2;
    private int ballance_;
    /**
     * <code>required int32 ballance = 2;</code>
     */
    public boolean hasBallance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 ballance = 2;</code>
     */
    public int getBallance() {
      return ballance_;
    }

    // required string localTask = 3;
    public static final int LOCALTASK_FIELD_NUMBER = 3;
    private Object localTask_;
    /**
     * <code>required string localTask = 3;</code>
     */
    public boolean hasLocalTask() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string localTask = 3;</code>
     */
    public String getLocalTask() {
      Object ref = localTask_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localTask_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string localTask = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocalTaskBytes() {
      Object ref = localTask_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        localTask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      punterId_ = 0;
      ballance_ = 0;
      localTask_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasPunterId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBallance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalTask()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, punterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, ballance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLocalTaskBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, punterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ballance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLocalTaskBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Billing parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Billing parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Billing parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Billing parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Billing parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Billing parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Billing parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Billing parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Billing parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Billing parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Billing prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.Billing}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements BillingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return BallanceReq.internal_static_tutorial_Billing_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return BallanceReq.internal_static_tutorial_Billing_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Billing.class, Builder.class);
      }

      // Construct using ru.splat.Billing.protobuf.BallanceReq.Billing.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        punterId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ballance_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        localTask_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return BallanceReq.internal_static_tutorial_Billing_descriptor;
      }

      public Billing getDefaultInstanceForType() {
        return Billing.getDefaultInstance();
      }

      public Billing build() {
        Billing result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Billing buildPartial() {
        Billing result = new Billing(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.punterId_ = punterId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ballance_ = ballance_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.localTask_ = localTask_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Billing) {
          return mergeFrom((Billing)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Billing other) {
        if (other == Billing.getDefaultInstance()) return this;
        if (other.hasPunterId()) {
          setPunterId(other.getPunterId());
        }
        if (other.hasBallance()) {
          setBallance(other.getBallance());
        }
        if (other.hasLocalTask()) {
          bitField0_ |= 0x00000004;
          localTask_ = other.localTask_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPunterId()) {
          
          return false;
        }
        if (!hasBallance()) {
          
          return false;
        }
        if (!hasLocalTask()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Billing parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Billing) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 punterId = 1;
      private int punterId_ ;
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public boolean hasPunterId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public int getPunterId() {
        return punterId_;
      }
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public Builder setPunterId(int value) {
        bitField0_ |= 0x00000001;
        punterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 punterId = 1;</code>
       */
      public Builder clearPunterId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        punterId_ = 0;
        onChanged();
        return this;
      }

      // required int32 ballance = 2;
      private int ballance_ ;
      /**
       * <code>required int32 ballance = 2;</code>
       */
      public boolean hasBallance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 ballance = 2;</code>
       */
      public int getBallance() {
        return ballance_;
      }
      /**
       * <code>required int32 ballance = 2;</code>
       */
      public Builder setBallance(int value) {
        bitField0_ |= 0x00000002;
        ballance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ballance = 2;</code>
       */
      public Builder clearBallance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ballance_ = 0;
        onChanged();
        return this;
      }

      // required string localTask = 3;
      private Object localTask_ = "";
      /**
       * <code>required string localTask = 3;</code>
       */
      public boolean hasLocalTask() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public String getLocalTask() {
        Object ref = localTask_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localTask_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLocalTaskBytes() {
        Object ref = localTask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          localTask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public Builder setLocalTask(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localTask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public Builder clearLocalTask() {
        bitField0_ = (bitField0_ & ~0x00000004);
        localTask_ = getDefaultInstance().getLocalTask();
        onChanged();
        return this;
      }
      /**
       * <code>required string localTask = 3;</code>
       */
      public Builder setLocalTaskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        localTask_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.Billing)
    }

    static {
      defaultInstance = new Billing(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.Billing)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Billing_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Billing_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020BillingReq.proto\022\010tutorial\"@\n\007Billing\022" +
      "\020\n\010punterId\030\001 \002(\005\022\020\n\010ballance\030\002 \002(\005\022\021\n\tl" +
      "ocalTask\030\003 \002(\tB(\n\031ru.splat.Billing.proto" +
      "bufB\013BallanceReq"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Billing_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Billing_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Billing_descriptor,
              new String[] { "PunterId", "Ballance", "LocalTask", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
